### ISSUE TITLE
JOSS review questions

### ISSUE THREAD

**Issue by wch** [xoopR/set6#55] opened 2020-09-29 22:03 UTC
This is for https://github.com/openjournals/joss-reviews/issues/2598.

Sorry to open a non-specific issue, but that seemed to make the most sense in this case (these individual questions didn't seem to deserve their own issues).

******

Is there a plan to implement `$isSubset` for union sets? Borrowing from one of the examples:

```R
a <- Set$new(1, 2, 3)
b <- Interval$new(1, Inf)
c <- b - a
c$print()
#> (1,2) ∪ (2,3) ∪ (3,+∞] 

c$isSubset(Set$new(1))
#> isSubset currently not implemented for this wrapper.
```

******

Also, some small typos in the paper. It has:

```
> c$print()
(1,2) U (2,3) U (3,+Inf] 
```

But it the output is now:

```
(1,2) ∪ (2,3) ∪ (3,+∞] 
```

It looks like the union symbols and infinity symbol are different from the current code compared to what's in the paper.

Update: I just noticed that the output of other code examples has similar inconsistencies -- the output when I run it has special mathematical symbols, but the output in the paper does not.

**Comment by RaphaelS1** [comment] 2020-09-30 07:58
Hi Winston,

Thanks for your review.

> Update: I just noticed that the output of other code examples has similar inconsistencies -- the output when I run it has special mathematical symbols, but the output in the paper does not.

The last paragraph of the summary in the paper: "The example below demonstrates construction of a set and interval, comparisons of these, the set complement operator, and printing of the final result. Note the example does not use unicode printing but that this is possible within the package."

Unicode printing is set to `l10n_info()$`UTF-8` by default. To reproduce the same printing as in the example just first run `useUnicode(TRUE)`. I can't remember if I choose not to use these symbols in the paper because of a problem with the markdown or just to have a consistent interface for uses of all platforms.

> Is there a plan to implement $isSubset for union sets?

Yes there are a few methods missing from wrappers, in most cases this is because I haven't worked out the most efficient implementation yet. Though in your specific example `c$contains(1)` is equivalent and `$contains` is implemented for all wrappers; therefore I'll most likely just implement it in a similar way, i.e. calling `$contains` on the set elements, but unsure for intervals how this would work at the moment

**Comment by dpsanders** [comment] 2020-10-13 18:47
What's the status here?

**Comment by RaphaelS1** [comment] 2020-10-13 18:52
That would be up to @wch , if he's happy we can close this issue

**Closed** 2020-10-16 14:50 UTC
